In [2]:
import tiles_loader

In [4]:
loader = tiles_loader.TilesLoader(r"C:\Users\pavlo.butenko\Downloads\tileset", 3, 4)

{(0, 0): 'ElectronTile0.png', (1, 0): 'ElectronTile1.png', (2, 0): 'ElectronTile2.png', (3, 0): 'ElectronTile3.png', (0, 1): 'ElectronTile4.png', (1, 1): 'ElectronTile5.png', (2, 1): 'ElectronTile6.png', (3, 1): 'ElectronTile7.png', (0, 2): 'ElectronTile8.png', (1, 2): 'ElectronTile9.png', (2, 2): 'ElectronTile10.png', (3, 2): 'ElectronTile11.png'}


In [5]:
import numpy as np


array = np.load(r"C:\Users\pavlo.butenko\Downloads\scannet_indices\scannet_indices\scene_data\train\scene0265_01.npz", allow_pickle=True)

# paths = array["image_paths"]

# print(paths[paths != None].shape)

print(array)
print(array.files)
print(array["name"])

NpzFile 'C:\\Users\\pavlo.butenko\\Downloads\\scannet_indices\\scannet_indices\\scene_data\\train\\scene0265_01.npz' with keys: name, score
['name', 'score']
[[ 265    1  939  978]
 [ 265    1  379 1062]
 [ 265    1  340  363]
 ...
 [ 265    1  481  712]
 [ 265    1  389 1202]
 [ 265    1 1139 1150]]
